// Copyright 2025 Palantir Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by datasource-generator; DO NOT EDIT.

package enrollment

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/palantir/terraform-provider-palantir-foundry/gateway-client/v2"
	"github.com/palantir/terraform-provider-palantir-foundry/internal/provider/helper"
	"github.com/palantir/terraform-provider-palantir-foundry/internal/provider/shared"
)

var (
	_ datasource.DataSource              = &enrollmentRoleAssignmentsDataSource{}
	_ datasource.DataSourceWithConfigure = &enrollmentRoleAssignmentsDataSource{}
)

func NewEnrollmentRoleAssignmentsDataSource() datasource.DataSource {
	return &enrollmentRoleAssignmentsDataSource{}
}

type enrollmentRoleAssignmentsDataSource struct {
	client            *v2.ClientWithResponses
	deletionsDisabled bool
}

func (d *enrollmentRoleAssignmentsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_enrollment_role_assignments"
}

func (d *enrollmentRoleAssignmentsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	r := &enrollmentRoleAssignmentsResource{}
	var resourceSchemaResp resource.SchemaResponse
	r.Schema(ctx, resource.SchemaRequest{}, &resourceSchemaResp)

	resp.Schema = helper.ConvertResourceSchemaToDataSource(
		resourceSchemaResp.Schema,
		"Data source for reading a Foundry EnrollmentRoleAssignments.",
	)
}

func (d *enrollmentRoleAssignmentsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*shared.FoundryProviderData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *shared.FoundryProviderData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	d.client = providerData.Client
	d.deletionsDisabled = providerData.Flags.DeletionsDisabled
}

func (d *enrollmentRoleAssignmentsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data enrollmentRoleAssignmentsResourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	r := &enrollmentRoleAssignmentsResource{
		client:            d.client,
		deletionsDisabled: d.deletionsDisabled,
	}

	var resourceReq resource.ReadRequest
	resourceReq.State.Raw = req.Config.Raw
	resourceReq.State.Schema = req.Config.Schema

	var resourceResp resource.ReadResponse
	resourceResp.State.Raw = resp.State.Raw
	resourceResp.State.Schema = resp.State.Schema

	r.Read(ctx, resourceReq, &resourceResp)

	resp.Diagnostics.Append(resourceResp.Diagnostics...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.State.Raw = resourceResp.State.Raw
	resp.State.Schema = resourceResp.State.Schema
}
